name: mydotnet

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./Src/SimpleCrmApi/SimpleCrmApi.csproj
    - name: Build
      run: dotnet build --no-restore ./Src/SimpleCrmApi/SimpleCrmApi.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal ./Src/SimpleCrmApi.Tests/SimpleCrmApi.Tests.csproj
    - name: Publish
      run: dotnet publish --framework netcoreapp3.1 --configuration Release --self-contained true -r linux-x64 --output ./mypublish ./Src/SimpleCrmApi/SimpleCrmApi.csproj
    - name: Upload ftp
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ${{ secrets.FTPHOST }}
        user: ${{ secrets.FTPUSER }}
        password: ${{ secrets.FTPPASSWORD }}
        localDir: "mypublish"
        remoteDir: "artefacts"
        options: "--delete --asci"
    - name: DeployScript
      uses: cross-the-world/ssh-pipeline@master
      env:
      WELCOME: "ssh pipeline"
      with:
        host: ${{ secrets.DC_HOST }}
        user: ${{ secrets.DC_USER }}
        pass: ${{ secrets.DC_PASS }}
        port: ${{ secrets.DC_PORT }}
        connect_timeout: 20s
        script: |
          mkdir /home/test1
